# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64f6ed1d3f67360a3f103d84fcfc7f8f5442c2f9918ab742fc88f2404bdc6ff681d38bbf676e45f6343d370b3b5447bbd03e20c9bf03b8476164dfddcbd5de77

test:
  secret_key_base: 78de371a23044874239e486265558b69e68dca23f51e9dff8a5688456819932b3b381c2b757c46fe29d595c7fb05a5f881bf3edac417491acf9531fe4c9cd9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
